version: '3.8'

services:
  nginx:
    container_name: nginx_container
    build: ./requirements/nginx
    ports:
      - "443:443"
    volumes:
      - ./requirements/nginx/html:/var/www/html
      - ./requirements/nginx/certs:/etc/nginx/certs:ro
    networks:
      - my_network
    restart: on-failure
  
  wordpress:
    container_name: wordpress_container
    build: ./requirements/wordpress
    depends_on:
      - mariadb
    volumes:
      - wordpress_data:/var/www/html
      - wordpress_db:/var/lib/mysql
    networks:
      - my_network
    environment:
      WORDPRESS_DB_HOST: mariadb
      WORDPRESS_DB_USER: ${MYSQL_USER}
      WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
    restart: on-failure
  
  mariadb:
    container_name: mariadb_container
    build: ./requirements/mariadb
    environment:
      MY_SQL_DATABASE: wordpress
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mariadb_db: /var/lib/mysql
    networks:
      - my_network
    restart: on-failure

volumes:
  wordpress_data:
  mariadb_db:

networks:
  my_network:
    driver: bridge
