version: '3'

services:
  mariadb:
    image: mariadb
    container_name: mariadb
    build: ./requirements/mariadb
    volumes:
      - db_data: /var/lib/mysql
    networks:
      - my_network
    restart: always
    env_file:
      - .env

  nginx:
    image: nginx
    container_name: nginx
    build: ./requirements/nginx
    volumes:
      - wordpress_data:/var/www/html
    depends_on:
      - wordpress
    networks:
      - my_network
    restart: always
    ports:
      - "443:443"
  
  wordpress:
    image: wordpress
    container_name: wordpress
    build: ./requirements/wordpress
    volumes:
      - wordpress_data: /var/www/html
    depends_on:
      - mariadb
    networks:
      - my_network
    restart: always
    env_file:
      - .env
  
volumes:
  wordpress_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${VOLUME_PATH}/wordpress
  db_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${VOLUME_PATH}/db

networks:
  my_network:
    driver: bridge
