version: '3'

services:
  mariadb:
    image: mariadb
    container_name: mariadb
    build: 
      context: ./requirements/mariadb
      args:
        WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
    volumes:
      - mariadb:/var/lib/mysql
    networks:
      - my_network
    restart: always
    env_file:
      - .env

  nginx:
    image: nginx
    container_name: nginx
    build: 
      context: ./requirements/nginx
      args:
        SSL_PATH: ${SSL_PATH}
    volumes:
      - wordpress:/var/www/html
    depends_on:
      - wordpress
    networks:
      - my_network
    restart: always
    env_file:
      - .env
  
  wordpress:
    image: wordpress
    container_name: wordpress
    build: 
      context: ./requirements/wordpress
    volumes:
      - wordpress:/var/www/html
    depends_on:
      - mariadb
    networks:
      - my_network
    restart: always
    env_file:
      - .env
  
volumes:
  wordpress:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${VOLUME_PATH}/wordpress
  mariadb:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${VOLUME_PATH}/db

networks:
  my_network:
    driver: bridge
