version: '3'

services:
  nginx:
    build:
      context: ./requirements/nginx
    ports:
      - "443:443"
    restart: always
  
  wordpress:
    build:
      context: ./requirements/wordpress
    volumes:
      - wordpress_data:/var/www/html
      - wordpress_db:/var/lib/mysql
    environment:
      WORDPRESS_DB_HOST: mariadb
      WORDPRESS_DB_USER: ${MYSQL_USER}
      WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
    depends_on:
      - mariadb
    restart: always
  
  mariadb:
    build:
      context: ./requirements/mariadb
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - wordpress_db: /var/lib/mysql
    restart: always

volumes:
  wordpress_data:
  wordpress_db:
